#!/data/data/com.termux/files/usr/bin/bash

termux-wake-lock

url="$1"

LOCKFILE="$HOME/.dlp_log/.yt-dlp.lock"
LOGDIR="$HOME/.dlp_log"
mkdir -p "$LOGDIR"

echo "What should I do with:"
echo "$url"
echo
echo "1) yt-dlp no-config"
echo "2) yt-dlp audio"
echo "3) yt-dlp split audio"
echo "4) yt-dlp 480"
echo "7) yt-dlp 720"
echo "0) yt-dlp mp3"
echo "g) gallery-dl"
echo "a) download aria2c"
echo "z) nothing"

run_bg() {
    (
        # Acquire an exclusive lock on the lockfile
        # This blocks execution until the previous download finishes
        exec 9>"$LOCKFILE"
        flock -x 9

        "$@"

        termux-media-scan "/storage/" >/dev/null 2>&1
        termux-wake-unlock
    ) >/dev/null 2>&1 & disown

    exit 0
}

new_log() {
    echo "$LOGDIR/$(date +%Y%m%d-%H%M%S).log"
}

while true; do
    printf "\nChoice: "

    read -rn 1 CHOICE
    echo

    case "$CHOICE" in

        1)
            logfile=$(new_log)

            run_bg \
            sh -c '
                yt-dlp \
                --no-config \
                --no-mtime \
                -o "%(webpage_url_domain)s/%(title)s [%(id)s].%(ext)s" \
                "$1" >> "$2" 2>&1
            ' sh "$url" "$logfile"
            ;;

        2)
            logfile=$(new_log)

            run_bg \
            sh -c '
                yt-dlp --x "$1" >> "$2" 2>&1
            ' sh "$url" "$logfile"
            ;;

        3)
            logfile=$(new_log)

            run_bg \
            sh -c '
                yt-dlp --xpl "$1" >> "$2" 2>&1
            ' sh "$url" "$logfile"
            ;;

        4)
            logfile=$(new_log)

            run_bg \
            sh -c '
                yt-dlp --4 "$1" >> "$2" 2>&1
            ' sh "$url" "$logfile"
            ;;

        7)
            logfile=$(new_log)

            run_bg \
            sh -c '
                yt-dlp --7 "$1" >> "$2" 2>&1
            ' sh "$url" "$logfile"
            ;;

        0)
            logfile=$(new_log)

            run_bg \
            sh -c '
                yt-dlp --xx "$1" >> "$2" 2>&1
            ' sh "$url" "$logfile"
            ;;

        g)
            gallery-dl "$url"
            termux-wake-unlock
            exit 0
            ;;

        a)
            aria2c \
                --seed-time=0 \
                "$url"

            termux-wake-unlock
            exit 0
            ;;

        z)
            echo "bye"
            termux-wake-unlock
            exit 0
            ;;

        *)
            echo "Invalid choice"
            ;;
    esac
done
